#!/bin/sh

set -e

if ! test $(which forever)
then
  echo
  echo "!!!!"
  echo "You don't have forever installed. You need to install it first."
  echo
  echo "Just install it with this command: "
  echo 'sudo npm install forever -g'
  echo
  exit 1
fi

mkdir -p log

npm install

if [ ! -f  config/config.json ]
then
  echo
  echo "==> Please create and edit your configuration at config/config.json."
  echo
  exit 0
fi

echo "Finished setting up Dasher! run it with script/server or install it with script/install."
